version: 2

jobs:
  build:
    environment:
      CIRCLE_TEST_RESULTS: $HOME/test-results
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      FASTLANE_ITUNES_TRANSPORTER_PATH: /usr/local/itms
    docker:
      - image: circleci/ruby:2.3
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout

      - restore_cache:
          key: fastlane-ubuntu-gems-{{ checksum "Gemfile" }}
      - run:
          name: Setup Build
          command: |
            mkdir -p $CIRCLE_TEST_RESULTS
            echo "2.3" > .ruby-version
            gem update --system
            bundle check || bundle install --jobs=4 --retry=3 --path .bundle
            sudo apt-get install shellcheck
      - run:
          name: Install additional dependency xar
          command: |
            cd /tmp
            mkdir download
            cd download
            wget https://github.com/downloads/mackyle/xar/xar-1.6.1.tar.gz
            tar -xzf xar-1.6.1.tar.gz
            cd xar-1.6.1
            ./autogen.sh --noconfigure
            ./configure
            make
            sudo make install
      - run:
          name: Install additional dependency iTMSTransporter
          command: |
            cd /tmp
            wget https://github.com/janpio/fastlane-ubuntu-foo/raw/master/iTMSTransporter_installer_linux_1.9.7.sh
            sudo sh iTMSTransporter_installer_linux_1.9.7.sh --target itms --noexec
            cd itms
            sudo sed -e '15,43d' -i install_script.sh
            sudo ./install_script.sh
      - save_cache:
          key: fastlane-v2-gems-{{ checksum "Gemfile" }}-b
          paths:
            - .bundle

      - run:
          name: Check PR Metadata
          command: bundle exec danger || echo "danger failed"

      - run: bundle exec fastlane test

      - store_test_results:
          path: /Users/distiller/test-results

      - run:
          name: Post Test Results to GitHub
          command: bundle exec danger || echo "danger failed"
          when: always # Run this even when tests fail
